### PR TITLE
More accurate docs to help for use

### PR DESCRIPTION
**Pull request by pimpin**
As long I can't manage to make it work...

May be false...

Should I keep 3 gems in my gemfile or cancan_strong_parameters his holding dependencies ?
Please correct or merge this.
Thanks for help

### CODE REVIEW

**Comment by colinyoung** [comment]
Hey @pimpin -

So, before we merge this, how is the gem not working for you?

`cancan` and `strong_parameters` are added to this gem's gemspec, but bundler is smart enough to handle a situation in which both `cancan_strong_parameters` and your local rails app have `cancan` and `strong_parameters` present.

So what was the error you were having trouble with?

**Comment by pimpin** [comment]
Hey @colinyoung -

There was no explicit error on bundling but on use, I never manage to assign my attributes.
It always raise ActiveModel::ForbiddenAttributes exception.
But I might have miss used it. That's why I ask more details on example in the readme, adapting the one from `strong_parameters`. My PR is probably not ok...

Thanks for help.

**Comment by colinyoung** [comment]
@pimpin  - good point, I will add some more info to the docs about `ActiveModel::ForbiddenAttributes`.

**Comment by pimpin** [comment]
Thanks @colinyoung for doc ! That's sound's clear. I might try it again soon.

**Pull request closed without merging**
